### ISSUE TITLE
Need patch to work with Keycloak 25.0.4

### ISSUE THREAD

**Issue by cesarbtt** [grnet/eidas-keycloak-extension#10]
This extension doesn't work with Keycloak 25.0.4. I have done that patch on this files

pom.xml
src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProviderFactory.java
src/main/java/gr/grnet/keycloak/idp/saml/EidasSAMLEndpoint.java

**Comment by sgflt** [comment]
Could you provide pull request?

**Comment by cesarbtt** [comment]
Hi.

  I attached you  a patch file. My job focused in two goals:
1) Compile it to work with Keycloak 25.0.4
2) Use it to integrate ***@***.*** identity provider (
https://clave.gob.es/clave_Home/clave.html)

  To achieve the first goal I modified some lines because there are
deprecated methods in some classes. To get ***@***.*** works I added an attribute
named "ProviderName" in the request header because it's mandatory in ***@***.***
implementation. Apart from that I added several log call only for debug
purposes but you can delete that.

Thanks in advance
   César Gallego

**Comment by cesarbtt** [comment]
From 3720bac84e721f1bc894020ae31e6d8cbfb5e925 Mon Sep 17 00:00:00 2001
From: cgallegocoruna <c.galego@coruna.es>
Date: Thu, 12 Sep 2024 13:24:01 +0200
Subject: [PATCH] =?UTF-8?q?Cambios=20para=20Keycloak=2025.0.4=20y=20adapta?=
 =?UTF-8?q?ci=C3=B3n=20a=20Cl@ve?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

---
 pom.xml                                       | 12 +++-
 .../idp/EidasSAMLIdentityProvider.java        | 24 +++++++-
 .../idp/EidasSAMLIdentityProviderFactory.java |  9 ++-
 .../keycloak/idp/saml/EidasSAMLEndpoint.java  | 60 +++++++++++++++----
 4 files changed, 90 insertions(+), 15 deletions(-)

diff --git a/pom.xml b/pom.xml
index 8473619..1f524a4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -28,11 +28,21 @@
 
 	<properties>
 		<javaVersion>17</javaVersion>
-		<keycloakVersion>24.0.4</keycloakVersion>
+		<keycloakVersion>25.0.4</keycloakVersion>
 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
 	</properties>
 
 	<dependencies>
+<dependency>
+    <groupId>org.jboss.resteasy</groupId>
+    <artifactId>resteasy-jaxrs</artifactId>
+    <version>3.9.3.SP1</version> 
+</dependency>
+<dependency> 
+    <groupId>commons-codec</groupId>
+    <artifactId>commons-codec</artifactId>
+    <version>1.15</version> 
+</dependency> 
 		<dependency>
 			<groupId>org.keycloak</groupId>
 			<artifactId>keycloak-saml-core</artifactId>
diff --git a/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProvider.java b/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProvider.java
index 4f30b49..6ac5ddd 100644
--- a/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProvider.java
+++ b/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProvider.java
@@ -104,20 +104,24 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 		super(session, config, destinationValidator);
 		this.config = config;
 		this.destinationValidator = destinationValidator;
+		logger.trace("Constructor EidasSAMLIdentityProvider: session=" + session + ", config=" + config + ", destinationValidator=" + destinationValidator);
 	}
 
 	@Override
 	public EidasSAMLIdentityProviderConfig getConfig() {
+		logger.trace("Método getConfig");
 		return this.config;
 	}
 
 	@Override
 	public Object callback(RealmModel realm, AuthenticationCallback callback, EventBuilder event) {
+		logger.trace("Método callback: realm=" + realm + ", callback=" + callback + ", event=" + event);
 		return new EidasSAMLEndpoint(session, this, getConfig(), callback, destinationValidator);
 	}
 
 	@Override
 	public Response performLogin(AuthenticationRequest request) {
+		logger.trace("Método performLogin: request=" + request);
 		try {
 			UriInfo uriInfo = request.getUriInfo();
 			RealmModel realm = request.getRealm();
@@ -215,10 +219,20 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 			// against the ID returned from the IdP
 			request.getAuthenticationSession().setClientNote(SamlProtocol.SAML_REQUEST_ID, authnRequest.getID());
 
+			logger.tracef("getConfig().getEntityId() = [%s]",getConfig().getEntityId());
+			Document documentoPeticion = authnRequestBuilder.toDocument();
+			if (documentoPeticion.getElementsByTagName("samlp:AuthnRequest")!=null && documentoPeticion.getElementsByTagName("samlp:AuthnRequest").getLength()>0 && getConfig().getEntityId()!=null) {
+				Element authnRequestElement = (Element) documentoPeticion.getElementsByTagName("samlp:AuthnRequest").item(0);
+				authnRequestElement.setAttribute("ProviderName", getConfig().getEntityId());
+			} else {
+				logger.info("SAML AuthnRequest NO ENCONTRADO o EntityID sin configurar");
+			}
+			logger.trace("SAML AuthnRequest ("+getConfig().getEntityId()+"): " + DocumentUtil.asString(documentoPeticion));
+
 			if (postBinding) {
-				return binding.postBinding(authnRequestBuilder.toDocument()).request(destinationUrl);
+				return binding.postBinding(documentoPeticion).request(destinationUrl);
 			} else {
-				return binding.redirectBinding(authnRequestBuilder.toDocument()).request(destinationUrl);
+				return binding.redirectBinding(documentoPeticion).request(destinationUrl);
 			}
 		} catch (Exception e) {
 			throw new IdentityBrokerException("Could not create authentication request.", e);
@@ -227,11 +241,13 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 
 	@Override
 	public IdentityProviderDataMarshaller getMarshaller() {
+		logger.trace("Método getMarshaller");
 		return new EidasSAMLDataMarshaller();
 	}
 
 	@Override
 	public Response export(UriInfo uriInfo, RealmModel realm, String format) {
+		logger.trace("Método export: uriInfo=" + uriInfo + ", realm=" + realm + ", format=" + format);
 		try {
 			URI authnResponseBinding = JBossSAMLURIConstants.SAML_HTTP_REDIRECT_BINDING.getUri();
 
@@ -400,6 +416,7 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 	}
 
 	private List<String> getAuthnContextClassRefUris() {
+		logger.trace("Método getAuthnContextClassRefUris");
 		String authnContextClassRefs = getConfig().getAuthnContextClassRefs();
 		if (authnContextClassRefs == null || authnContextClassRefs.isEmpty())
 			return new LinkedList<String>();
@@ -413,6 +430,7 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 	}
 
 	private List<String> getAuthnContextDeclRefUris() {
+		logger.trace("Método getAuthnContextDeclRefUris");
 		String authnContextDeclRefs = getConfig().getAuthnContextDeclRefs();
 		if (authnContextDeclRefs == null || authnContextDeclRefs.isEmpty())
 			return new LinkedList<String>();
@@ -426,6 +444,7 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 	}
 
 	private String getEntityId(UriInfo uriInfo, RealmModel realm) {
+		logger.trace("Método getEntityId: uriInfo=" + uriInfo + ", realm=" + realm);
 		String configEntityId = getConfig().getEntityId();
 
 		if (configEntityId == null || configEntityId.isEmpty())
@@ -435,6 +454,7 @@ public class EidasSAMLIdentityProvider extends SAMLIdentityProvider {
 	}
 
 	private void updateExtensionsType(SPSSODescriptorType spDescriptor, String nodeCountry) {
+		logger.trace("Método updateExtensionsType: spDescriptor=" + spDescriptor + ", nodeCountry=" + nodeCountry);
 		ExtensionsType extensions = spDescriptor.getExtensions();
 		if (extensions == null) {
 			extensions = new ExtensionsType();
diff --git a/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProviderFactory.java b/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProviderFactory.java
index 029fdcb..d10245f 100644
--- a/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProviderFactory.java
+++ b/src/main/java/gr/grnet/keycloak/idp/EidasSAMLIdentityProviderFactory.java
@@ -121,10 +121,15 @@ public class EidasSAMLIdentityProviderFactory implements IdentityProviderFactory
 	public void close() {
 	}
 
+    
+
     @Override
-    public Map<String, String> parseConfig(KeycloakSession session, InputStream inputStream) {
+    //public Map<String, String> parseConfig(KeycloakSession session, InputStream inputStream) {
+    public Map<String, String> parseConfig(KeycloakSession session, String config) {
         try {
-            EntityDescriptorType entityType = SAMLMetadataUtil.parseEntityDescriptorType(inputStream);
+            //InputStream inputStream = new java.io.ByteArrayInputStream(config.getBytes(java.nio.charset.StandardCharsets.UTF_8)); // {{ edit_1 }}
+
+            EntityDescriptorType entityType = SAMLMetadataUtil.parseEntityDescriptorType(config);
             IDPSSODescriptorType idpDescriptor = SAMLMetadataUtil.locateIDPSSODescriptorType(entityType);
 
             if (idpDescriptor != null) {
diff --git a/src/main/java/gr/grnet/keycloak/idp/saml/EidasSAMLEndpoint.java b/src/main/java/gr/grnet/keycloak/idp/saml/EidasSAMLEndpoint.java
index fa42067..dda137b 100644
--- a/src/main/java/gr/grnet/keycloak/idp/saml/EidasSAMLEndpoint.java
+++ b/src/main/java/gr/grnet/keycloak/idp/saml/EidasSAMLEndpoint.java
@@ -312,7 +312,7 @@ public class EidasSAMLEndpoint {
                     logger.error("validation failed", e);
                     event.event(EventType.IDENTITY_PROVIDER_RESPONSE);
                     event.error(Errors.INVALID_SIGNATURE);
-                    return ErrorPage.error(session, null, Response.Status.BAD_REQUEST, Messages.INVALID_REQUESTER);
+                    return ErrorPage.error(session, null, Response.Status.BAD_REQUEST, Messages.INVALID_REQUESTER);                   
                 }
             }
 
@@ -321,7 +321,6 @@ public class EidasSAMLEndpoint {
                 event.event(EventType.LOGOUT);
                 LogoutRequestType logout = (LogoutRequestType) requestAbstractType;
                 return logoutRequest(logout, relayState);
-
             } else {
                 event.event(EventType.LOGIN);
                 event.error(Errors.INVALID_TOKEN);
@@ -420,6 +419,14 @@ public class EidasSAMLEndpoint {
 
         protected Response handleLoginResponse(String samlResponse, SAMLDocumentHolder holder, ResponseType responseType, String relayState, String clientId) {
 
+            logger.debug("### handleLoginResponse ###########################################");
+            logger.debugf("samlResponse: %s", samlResponse);
+            logger.debugf("holder: %s", holder);
+            logger.debugf("responseType: %s", responseType);
+            logger.debugf("relayState: %s", relayState);
+            logger.debugf("clientId: %s", clientId);
+            logger.debug("###################################################################");
+
             try {
                 AuthenticationSessionModel authSession;
                 if (StringUtil.isNotBlank(clientId)) {
@@ -491,8 +498,13 @@ public class EidasSAMLEndpoint {
 
                 boolean signed = AssertionUtil.isSignedElement(assertionElement);
                 final boolean assertionSignatureNotExistsWhenRequired = config.isWantAssertionsSigned() && !signed;
+                logger.debugf("Valores de assertionSignatureNotExistsWhenRequired %s | %s", config.isWantAssertionsSigned(), signed);
+
                 final boolean signatureNotValid = signed && config.isValidateSignature() && !AssertionUtil.isSignatureValid(assertionElement, getIDPKeyLocator());
+                logger.debugf("Valores de signatureNotValid %s | %s", config.isValidateSignature(), AssertionUtil.isSignatureValid(assertionElement, getIDPKeyLocator()));
+
                 final boolean hasNoSignatureWhenRequired = ! signed && config.isValidateSignature() && ! containsUnencryptedSignature(holder);
+                logger.debugf("Valores de assertionSignatureNotExistsWhenRequired %s", containsUnencryptedSignature(holder));
 
                 if (assertionSignatureNotExistsWhenRequired || signatureNotValid || hasNoSignatureWhenRequired) {
                     logger.error("validation failed");
@@ -526,7 +538,23 @@ public class EidasSAMLEndpoint {
 
                 NameIDType subjectNameID = getSubjectNameID(assertion);
                 String principal = getPrincipal(assertion);
-
+                logger.debugf("Assertion details: %s", assertion); // Agregado para mostrar detalles de assertion
+                logger.debugf("Assertion ID: %s", assertion.getID());
+                logger.debugf("Assertion Issue Instant: %s", assertion.getIssueInstant());
+                logger.debugf("Assertion Issuer: %s", assertion.getIssuer() != null ? assertion.getIssuer().getValue() : "null");
+                logger.debugf("Assertion Subject: %s", assertion.getSubject() != null ? assertion.getSubject().toString() : "null");
+                logger.debugf("Assertion Conditions: %s", assertion.getConditions() != null ? assertion.getConditions().toString() : "null");
+                logger.debugf("Assertion Attribute Statements: %s", assertion.getAttributeStatements() != null ? assertion.getAttributeStatements().toString() : "null");
+                // Detalle de Attribute Statements
+                logger.debugf("Número de Attribute Statements: %d", assertion.getAttributeStatements() != null ? assertion.getAttributeStatements().size() : 0);
+
+                String firstName = getAttributeByFriendlyName(assertion, "FirstName"); // Inicializa FirstName
+                logger.debugf("FirstName: %s", firstName); // Agregado para depurar FirstName
+
+                String familyName = getAttributeByFriendlyName(assertion, "FamilyName"); // Inicializa FamilyName
+                logger.debugf("FamilyName: %s", familyName); // Agregado para depurar FamilyName
+
+                logger.debugf("Principal: %s", principal);
                 if (principal == null) {
                     logger.errorf("no principal in assertion; expected: %s", expectedPrincipalType());
                     event.event(EventType.IDENTITY_PROVIDER_RESPONSE);
@@ -534,16 +562,21 @@ public class EidasSAMLEndpoint {
                     return ErrorPage.error(session, authSession, Response.Status.BAD_REQUEST, Messages.INVALID_REQUESTER);
                 }
 
-                //Map<String, String> notes = new HashMap<>();
-                BrokeredIdentityContext identity = new BrokeredIdentityContext(principal);
+                BrokeredIdentityContext identity = new BrokeredIdentityContext(principal, config);
                 identity.getContextData().put(SAML_LOGIN_RESPONSE, responseType);
                 identity.getContextData().put(SAML_ASSERTION, assertion);
                 identity.setAuthenticationSession(authSession);
-
                 identity.setUsername(principal);
 
+                // Asigna los valores a identity
+                identity.setFirstName(firstName); // Asignar FirstName
+                identity.setLastName(familyName); //
+                identity.setUserAttribute("samlResponse",samlResponse);
+
+                
                 //SAML Spec 2.2.2 Format is optional
                 if (subjectNameID != null && subjectNameID.getFormat() != null && subjectNameID.getFormat().toString().equals(JBossSAMLURIConstants.NAMEID_FORMAT_EMAIL.get())) {
+                    logger.debugf("Setting email to %s", subjectNameID.getValue());
                     identity.setEmail(subjectNameID.getValue());
                 }
 
@@ -586,13 +619,13 @@ public class EidasSAMLEndpoint {
 
                 String brokerUserId = config.getAlias() + "." + principal;
                 identity.setBrokerUserId(brokerUserId);
-                identity.setIdpConfig(config);
+                logger.debug("Para que compile comento el setIdpConfig");
+                //identity.setIdpConfig(config);
                 identity.setIdp(provider);
                 if (authn != null && authn.getSessionIndex() != null) {
                     identity.setBrokerSessionId(config.getAlias() + "." + authn.getSessionIndex());
                  }
 
-
                 return callback.authenticated(identity);
             } catch (WebApplicationException e) {
                 return e.getResponse();
@@ -677,6 +710,7 @@ public class EidasSAMLEndpoint {
                     event.event(EventType.IDENTITY_PROVIDER_RESPONSE);
                     event.error(Errors.INVALID_SIGNATURE);
                     return ErrorPage.error(session, null, Response.Status.BAD_REQUEST, Messages.INVALID_FEDERATED_IDENTITY_ACTION);
+                    
                 }
             }
             if (statusResponse instanceof ResponseType) {
@@ -807,14 +841,20 @@ public class EidasSAMLEndpoint {
     private String getPrincipal(AssertionType assertion) {
 
         SamlPrincipalType principalType = config.getPrincipalType();
+        logger.debugf("Principal Type: %s", principalType); // Log del tipo de principal
 
         if (principalType == null || principalType.equals(SamlPrincipalType.SUBJECT)) {
             NameIDType subjectNameID = getSubjectNameID(assertion);
+            logger.debugf("Subject NameID: %s", subjectNameID != null ? subjectNameID.getValue() : "null"); // Log del NameID
             return subjectNameID != null ? subjectNameID.getValue() : null;
         } else if (principalType.equals(SamlPrincipalType.ATTRIBUTE)) {
-            return getAttributeByName(assertion, config.getPrincipalAttribute());
+            String attributeValue = getAttributeByName(assertion, config.getPrincipalAttribute());
+            logger.debugf("Attribute Value: %s", attributeValue); // Log del valor del atributo
+            return attributeValue;
         } else {
-            return getAttributeByFriendlyName(assertion, config.getPrincipalAttribute());
+            String friendlyAttributeValue = getAttributeByFriendlyName(assertion, config.getPrincipalAttribute());
+            logger.debugf("Friendly Attribute Value: %s", friendlyAttributeValue); // Log del valor del atributo amigable
+            return friendlyAttributeValue;
         }
 
     }
-- 
2.36.1.windows.1

**Comment by cesarbtt** [comment]
`
[cambios.patch](https://github.com/user-attachments/files/16978391/cambios.patch)
`

**Comment by dhm-msd** [comment]
Thanks for the patch @cesarbtt. 

New version has been released.
